/**:
  ros__parameters:
    general:
      grab_resolution: 'HD720'
      pub_resolution: 'NATIVE'
    depth:
      depth_mode: 'NEURAL'
      depth_confidence: 100
      depth_texture_conf: 100
      remove_saturated_areas: false
      min_depth: 0.1
      max_depth: 10.0